# Data Cleansing

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")
data_train = pd.read_csv("input/train_feature.csv") #训练数据
data_train_y = pd.read_csv("input/train_label.csv") #训练标签
data_test = pd.read_csv("input/test_feature.csv") #测试数据

# 对训练集reshape 8时刻合一天 ，维度增加到64维，最后再清洗去掉重复列

In [2]:
train_feature = data_train.values.ravel().reshape(-1)
print(train_feature, '\n shape :', train_feature.shape, '=', 17008 * 8)
feature_train_64 = train_feature.reshape([2126, 64])
print(feature_train_64, '\nshape :', feature_train_64.shape)

[ 1.00e+00  2.00e+00  0.00e+00 ... -8.00e-01  1.60e+01  6.96e+04] 
 shape : (136064,) = 136064
[[ 1.000e+00  2.000e+00  0.000e+00 ... -4.800e+00  4.200e+01  6.970e+04]
 [ 2.000e+00  2.000e+00  0.000e+00 ... -5.400e+00  4.800e+01  6.950e+04]
 [ 3.000e+00  2.000e+00  0.000e+00 ... -3.800e+00  2.900e+01  6.950e+04]
 ...
 [ 2.124e+03  2.000e+00  0.000e+00 ... -2.100e+00  1.400e+01  7.020e+04]
 [ 2.125e+03  2.000e+00  0.000e+00 ... -1.000e-01  1.000e+01  6.970e+04]
 [ 2.126e+03  2.000e+00  0.000e+00 ... -8.000e-01  1.600e+01  6.960e+04]] 
shape : (2126, 64)


# 对测试集reshape 8时刻合一天，维度增加到64维，最后再清洗去掉重复列

In [3]:
test_feature = data_test.values.ravel().reshape(-1)
print(test_feature, '\n shape :', test_feature.shape, '=', 7296 * 8)
feature_test_64 = test_feature.reshape([912, 64])
print(feature_test_64, '\nshape :', feature_test_64.shape)

[1.00e+00 2.00e+00 0.00e+00 ... 1.84e+01 1.70e+01 6.95e+04] 
 shape : (58368,) = 58368
[[ 1.00e+00  2.00e+00  0.00e+00 ... -8.70e+00  2.10e+01  6.91e+04]
 [ 2.00e+00  2.00e+00  0.00e+00 ... -9.40e+00  2.00e+01  6.96e+04]
 [ 3.00e+00  2.00e+00  0.00e+00 ... -7.00e+00  1.10e+01  7.00e+04]
 ...
 [ 9.10e+02  2.00e+00  0.00e+00 ...  1.70e+01  4.10e+01  6.97e+04]
 [ 9.11e+02  2.00e+00  0.00e+00 ...  1.97e+01  2.10e+01  6.95e+04]
 [ 9.12e+02  2.00e+00  0.00e+00 ...  1.84e+01  1.70e+01  6.95e+04]] 
shape : (912, 64)


# 数据简单清洗，

In [5]:
feature_name = data_train.columns.tolist()
feature_name.remove('日期')
time = data_train['时刻'][0:8].tolist()
feature_list = []
for j in time:
    feature_list.append('日期')
    for i in feature_name:
        fn = i+'_'+str(j)
        feature_list.append(fn)
        
len(feature_list)
print(feature_list)

['日期', '时刻_2', '辐照度_2', '风速_2', '风向_2', '温度_2', '湿度_2', '气压_2', '日期', '时刻_5', '辐照度_5', '风速_5', '风向_5', '温度_5', '湿度_5', '气压_5', '日期', '时刻_8', '辐照度_8', '风速_8', '风向_8', '温度_8', '湿度_8', '气压_8', '日期', '时刻_11', '辐照度_11', '风速_11', '风向_11', '温度_11', '湿度_11', '气压_11', '日期', '时刻_14', '辐照度_14', '风速_14', '风向_14', '温度_14', '湿度_14', '气压_14', '日期', '时刻_17', '辐照度_17', '风速_17', '风向_17', '温度_17', '湿度_17', '气压_17', '日期', '时刻_20', '辐照度_20', '风速_20', '风向_20', '温度_20', '湿度_20', '气压_20', '日期', '时刻_23', '辐照度_23', '风速_23', '风向_23', '温度_23', '湿度_23', '气压_23']


# 对训练集进行操作

In [6]:
# 转换成DataFrame类型的数据
data_train = pd.DataFrame(feature_train_64,columns = feature_list)
data_train.head()

日期  时刻_2  辐照度_2  风速_2   风向_2  温度_2  湿度_2     气压_2   日期  时刻_5   ...     \
0  1.0   2.0    0.0   2.1  343.0  -7.2  51.0  69800.0  1.0   5.0   ...      
1  2.0   2.0    0.0   1.1   45.0  -5.2  46.0  69800.0  2.0   5.0   ...      
2  3.0   2.0    0.0   2.9  278.0  -7.4  58.0  69500.0  3.0   5.0   ...      
3  4.0   2.0    0.0   0.3   90.0  -6.1  38.0  69500.0  4.0   5.0   ...      
4  5.0   2.0    0.0   1.4  231.0  -9.9  33.0  69100.0  5.0   5.0   ...      

   湿度_20    气压_20   日期  时刻_23  辐照度_23  风速_23  风向_23  温度_23  湿度_23    气压_23  
0   40.0  69700.0  1.0   23.0     0.0    0.8   14.0   -4.8   42.0  69700.0  
1   45.0  69400.0  2.0   23.0     0.0    2.5  297.0   -5.4   48.0  69500.0  
2   30.0  69500.0  3.0   23.0     0.0    0.8  140.0   -3.8   29.0  69500.0  
3   21.0  69100.0  4.0   23.0     0.0    0.8  270.0   -6.3   26.0  69200.0  
4   26.0  69200.0  5.0   23.0     0.0    1.1   63.0   -7.5   28.0  69300.0  

[5 rows x 64 columns]

In [7]:
# 去除重复列
columns = data_train.columns.tolist()
data_train_deal = data_train[columns].T.drop_duplicates().T
data_train_deal.head()

日期  时刻_2  辐照度_2  风速_2   风向_2  温度_2  湿度_2     气压_2  时刻_5  风速_5   ...     \
0  1.0   2.0    0.0   2.1  343.0  -7.2  51.0  69800.0   5.0   3.6   ...      
1  2.0   2.0    0.0   1.1   45.0  -5.2  46.0  69800.0   5.0   1.2   ...      
2  3.0   2.0    0.0   2.9  278.0  -7.4  58.0  69500.0   5.0   3.1   ...      
3  4.0   2.0    0.0   0.3   90.0  -6.1  38.0  69500.0   5.0   2.1   ...      
4  5.0   2.0    0.0   1.4  231.0  -9.9  33.0  69100.0   5.0   1.5   ...      

   风向_20  温度_20  湿度_20    气压_20  时刻_23  风速_23  风向_23  温度_23  湿度_23    气压_23  
0   66.0   -3.5   40.0  69700.0   23.0    0.8   14.0   -4.8   42.0  69700.0  
1  294.0   -3.8   45.0  69400.0   23.0    2.5  297.0   -5.4   48.0  69500.0  
2  225.0   -3.8   30.0  69500.0   23.0    0.8  140.0   -3.8   29.0  69500.0  
3   90.0   -3.0   21.0  69100.0   23.0    0.8  270.0   -6.3   26.0  69200.0  
4  297.0   -6.1   26.0  69200.0   23.0    1.1   63.0   -7.5   28.0  69300.0  

[5 rows x 55 columns]

## 合并数据集，将训练数据和标签合并

In [8]:
data_train_final = pd.concat([data_train_deal,data_train_y['电场实际太阳辐射指数']],axis = 1,join='inner')
data_train_final.head()

日期  时刻_2  辐照度_2  风速_2   风向_2  温度_2  湿度_2     气压_2  时刻_5  风速_5     ...      \
0  1.0   2.0    0.0   2.1  343.0  -7.2  51.0  69800.0   5.0   3.6     ...       
1  2.0   2.0    0.0   1.1   45.0  -5.2  46.0  69800.0   5.0   1.2     ...       
2  3.0   2.0    0.0   2.9  278.0  -7.4  58.0  69500.0   5.0   3.1     ...       
3  4.0   2.0    0.0   0.3   90.0  -6.1  38.0  69500.0   5.0   2.1     ...       
4  5.0   2.0    0.0   1.4  231.0  -9.9  33.0  69100.0   5.0   1.5     ...       

   温度_20  湿度_20    气压_20  时刻_23  风速_23  风向_23  温度_23  湿度_23    气压_23  \
0   -3.5   40.0  69700.0   23.0    0.8   14.0   -4.8   42.0  69700.0   
1   -3.8   45.0  69400.0   23.0    2.5  297.0   -5.4   48.0  69500.0   
2   -3.8   30.0  69500.0   23.0    0.8  140.0   -3.8   29.0  69500.0   
3   -3.0   21.0  69100.0   23.0    0.8  270.0   -6.3   26.0  69200.0   
4   -6.1   26.0  69200.0   23.0    1.1   63.0   -7.5   28.0  69300.0   

   电场实际太阳辐射指数  
0    0.108799  
1    0.130559  
2    0.114239  
3    0.081599  
4    0.212158  

[5 rows x 56 columns]

# 对测试集进行操作

In [9]:
data_test_deal = pd.DataFrame(feature_test_64,columns = feature_list)
data_test_deal.head()

日期  时刻_2  辐照度_2  风速_2   风向_2  温度_2  湿度_2     气压_2   日期  时刻_5   ...     \
0  1.0   2.0    0.0   1.3  257.0  -8.6  34.0  68600.0  1.0   5.0   ...      
1  2.0   2.0    0.0  13.8  288.0 -10.7  28.0  69300.0  2.0   5.0   ...      
2  3.0   2.0    0.0   9.6  274.0 -12.1  24.0  69700.0  3.0   5.0   ...      
3  4.0   2.0    0.0   7.5  278.0 -10.3  15.0  70000.0  4.0   5.0   ...      
4  5.0   2.0    0.0   5.1  276.0  -8.1  16.0  69600.0  5.0   5.0   ...      

   湿度_20    气压_20   日期  时刻_23  辐照度_23  风速_23  风向_23  温度_23  湿度_23    气压_23  
0   19.0  68900.0  1.0   23.0     0.0   14.9  286.0   -8.7   21.0  69100.0  
1   16.0  69400.0  2.0   23.0     0.0   11.6  280.0   -9.4   20.0  69600.0  
2    9.0  69800.0  3.0   23.0     0.0   12.1  281.0   -7.0   11.0  70000.0  
3   14.0  69500.0  4.0   23.0     0.0    3.3  272.0   -6.1   20.0  69500.0  
4   20.0  68700.0  5.0   23.0     0.0    1.6  333.0   -2.9   24.0  68700.0  

[5 rows x 64 columns]

In [11]:
data_test_deal.columns.tolist()

['日期',
 '时刻_2',
 '辐照度_2',
 '风速_2',
 '风向_2',
 '温度_2',
 '湿度_2',
 '气压_2',
 '日期',
 '时刻_5',
 '辐照度_5',
 '风速_5',
 '风向_5',
 '温度_5',
 '湿度_5',
 '气压_5',
 '日期',
 '时刻_8',
 '辐照度_8',
 '风速_8',
 '风向_8',
 '温度_8',
 '湿度_8',
 '气压_8',
 '日期',
 '时刻_11',
 '辐照度_11',
 '风速_11',
 '风向_11',
 '温度_11',
 '湿度_11',
 '气压_11',
 '日期',
 '时刻_14',
 '辐照度_14',
 '风速_14',
 '风向_14',
 '温度_14',
 '湿度_14',
 '气压_14',
 '日期',
 '时刻_17',
 '辐照度_17',
 '风速_17',
 '风向_17',
 '温度_17',
 '湿度_17',
 '气压_17',
 '日期',
 '时刻_20',
 '辐照度_20',
 '风速_20',
 '风向_20',
 '温度_20',
 '湿度_20',
 '气压_20',
 '日期',
 '时刻_23',
 '辐照度_23',
 '风速_23',
 '风向_23',
 '温度_23',
 '湿度_23',
 '气压_23']

In [12]:
#将重复列去掉
columns = data_test_deal.columns.tolist()
data_test_final = data_test_deal[columns].T.drop_duplicates().T
data_test_final.head()

日期  时刻_2  辐照度_2  风速_2   风向_2  温度_2  湿度_2     气压_2  时刻_5  风速_5   ...     \
0  1.0   2.0    0.0   1.3  257.0  -8.6  34.0  68600.0   5.0   4.5   ...      
1  2.0   2.0    0.0  13.8  288.0 -10.7  28.0  69300.0   5.0  12.0   ...      
2  3.0   2.0    0.0   9.6  274.0 -12.1  24.0  69700.0   5.0   9.5   ...      
3  4.0   2.0    0.0   7.5  278.0 -10.3  15.0  70000.0   5.0   5.2   ...      
4  5.0   2.0    0.0   5.1  276.0  -8.1  16.0  69600.0   5.0   3.7   ...      

   风向_20  温度_20  湿度_20    气压_20  时刻_23  风速_23  风向_23  温度_23  湿度_23    气压_23  
0  275.0   -6.3   19.0  68900.0   23.0   14.9  286.0   -8.7   21.0  69100.0  
1  288.0   -6.8   16.0  69400.0   23.0   11.6  280.0   -9.4   20.0  69600.0  
2  286.0   -4.1    9.0  69800.0   23.0   12.1  281.0   -7.0   11.0  70000.0  
3  227.0   -3.9   14.0  69500.0   23.0    3.3  272.0   -6.1   20.0  69500.0  
4   90.0   -1.0   20.0  68700.0   23.0    1.6  333.0   -2.9   24.0  68700.0  

[5 rows x 55 columns]

# 使用随机切分数据集 数据不进行标准化

In [26]:
from sklearn.cross_validation import train_test_split
from sklearn.cross_validation import cross_val_score
X = np.array(data_train_final.drop(['电场实际太阳辐射指数'],axis = 1))
y = np.array(data_train_y['电场实际太阳辐射指数'])
print(X.shape,y.shape)

((2126, 55), (2126,))

In [27]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.3,random_state = 45)
(X_train.shape,X_test.shape,y_train.shape,y_test.shape)

((1488, 55), (638, 55), (1488,), (638,))

In [28]:
X_test2 = np.array(data_test_final)
X_test2.shape

(912, 55)

# 数据标准化 归一化

In [51]:
from sklearn.preprocessing import StandardScaler
#标准化
scaler_train = StandardScaler().fit(X)
X_train_std = scaler_train.transform(X)
print(X_train_std.shape)
X_train_std,X_test_std,y_train_std,y_test_std = train_test_split(X_train_std,y,test_size = 0.3,random_state = 45)
print(X_train.shape,X_test.shape,y_train.shape,y_test.shape)

#对测试集进行标准化
scaler_test = StandardScaler().fit(X_test2)
X_test_std = scaler_test.transform(X_test2)
print(X_test_std.shape)

(2126, 55)
(1488, 55) (638, 55) (1488,) (638,)
(912, 55)


# 使用线性回归模型

In [42]:
from sklearn import linear_model
reg = linear_model.LinearRegression()
reg.fit(X_train_std,y_train_std)
y_pred_line = reg.predict(X_test_std)
y_pred_line

array([0.25257523, 0.30967674, 0.69971569, 0.26948114, 0.60890579,
       0.2435647 , 0.52245597, 0.43033593, 0.54621043, 0.38065096,
       0.27566494, 0.31134138, 0.35539397, 0.64667418, 0.51899102,
       0.33848752, 0.37657536, 0.40110327, 0.42384499, 0.30426964,
       0.49004686, 0.54897104, 0.36106617, 0.63757573, 0.22635213,
       0.45542646, 0.65797655, 0.67674691, 0.58964307, 0.7189508 ,
       0.38810989, 0.26643465, 0.60383851, 0.63768854, 0.34575367,
       0.3180565 , 0.38632763, 0.48463925, 0.47512553, 0.39383907,
       0.5589703 , 0.39119767, 0.30019708, 0.3879609 , 0.64366808,
       0.46966933, 0.31790874, 0.45035918, 0.50403685, 0.42189331,
       0.33380472, 0.42812963, 0.52676438, 0.58258403, 0.48552472,
       0.37925268, 0.41933327, 0.62040639, 0.33369062, 0.73943187,
       0.30038797, 0.66418416, 0.34313204, 0.32344595, 0.40257497,
       0.63099922, 0.40124291, 0.28676614, 0.39277427, 0.26396759,
       0.33679116, 0.47065432, 0.60051316, 0.42107506, 0.64154

In [43]:
from sklearn.metrics import mean_absolute_error
mae_xgb = mean_absolute_error(y_pred,y_test)
mae_line = mean_absolute_error(y_pred_line,y_test)
print("MAE xgb_score:",mae_xgb)
print("MAE line_score:",mae_line)

MAE xgb_score: 0.18524577575846843
MAE line_score: 0.17456017248187736


In [48]:
index = np.array(data_test_final['日期']).astype("int32")
index

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
       105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
       118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130,
       131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143,
       144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156,
       157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169,
       170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 18

In [52]:
import datetime
now = datetime.datetime.now()
now = now.strftime('%m-%d-%H-%M')

#y_hat = model.predict(X_test_64) #xgb模型
y_hat_line = reg.predict(X_test_std)
result = pd.DataFrame({"time":index,"prediction":y_hat_line})
columns = ["time","prediction"]
result = result.loc[:,columns]
result.to_csv("output/submit_baseline_line{}.csv".format(now),index = False)